insert into TacGia (id, tenTacGia) values (1, 'Roxanne Lewsey');
insert into TacGia (id, tenTacGia) values (2, 'Kanya Hame');
insert into TacGia (id, tenTacGia) values (3, 'Linn Cristofalo');
insert into TacGia (id, tenTacGia) values (4, 'Vincenty Slatcher');
insert into TacGia (id, tenTacGia) values (5, 'Addie Ovey');
insert into TacGia (id, tenTacGia) values (6, 'Vivi Dreinan');
insert into TacGia (id, tenTacGia) values (7, 'Ania Mee');
insert into TacGia (id, tenTacGia) values (8, 'Carolan Axup');
insert into TacGia (id, tenTacGia) values (9, 'Ronny Stickens');
insert into TacGia (id, tenTacGia) values (10, 'Brian Daulton');
insert into TacGia (id, tenTacGia) values (11, 'Francoise Dufour');
insert into TacGia (id, tenTacGia) values (12, 'Kaleena Songust');
insert into TacGia (id, tenTacGia) values (13, 'Ashlan Reburn');
insert into TacGia (id, tenTacGia) values (14, 'Isis Soppit');
insert into TacGia (id, tenTacGia) values (15, 'Timmi Siveter');
insert into TacGia (id, tenTacGia) values (16, 'Adan Kilbride');
insert into TacGia (id, tenTacGia) values (17, 'Andonis Thal');
insert into TacGia (id, tenTacGia) values (18, 'Merry McCooke');
insert into TacGia (id, tenTacGia) values (19, 'Aime Gaydon');
insert into TacGia (id, tenTacGia) values (20, 'Jason Dibdall');
insert into TacGia (id, tenTacGia) values (21, 'Farr Tarburn');
insert into TacGia (id, tenTacGia) values (22, 'Reggi McPhilemy');
insert into TacGia (id, tenTacGia) values (23, 'Arden Riby');
insert into TacGia (id, tenTacGia) values (24, 'Laurie Gerdts');
insert into TacGia (id, tenTacGia) values (25, 'Broddie Entwistle');
insert into TacGia (id, tenTacGia) values (26, 'Agata Lotwich');
insert into TacGia (id, tenTacGia) values (27, 'Gabbey Duchesne');
insert into TacGia (id, tenTacGia) values (28, 'Blanca Clout');
insert into TacGia (id, tenTacGia) values (29, 'Ede Maudling');
insert into TacGia (id, tenTacGia) values (30, 'Bone Bascombe');


insert into Sach (id, tenSach, namXuatBan,idTacGia) values (1, 'Opela', '2023',1);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (2, 'Lotlux', '2023',2);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (3, 'Stringtough', '2023',3);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (4, 'Matsoft', '2023',4);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (5, 'Hatity', '2023',5);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (6, 'Toughjoyfax', '2023',5);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (7, 'Domainer', '2023',7);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (8, 'Andalax', '2022',8);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (9, 'Sonair', '2023',9);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (10, 'Holdlamis', '2023',10);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (11, 'Konklab', '2022',11);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (12, 'Daltfresh', '2022',12);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (13, 'Asoka', '2023',13);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (14, 'Rank', '2023',14);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (15, 'Zaam-Dox', '2023',15);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (16, 'Prodder', '2022',16);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (17, 'Domainer', '2023',17);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (18, 'Bytecard', '2023',18);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (19, 'Overhold', '2023',19);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (20, 'Latlux', '2022',20);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (21, 'Zamit', '2023',21);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (22, 'Biodex', '2022',22);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (23, 'Fixflex', '2023',23);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (24, 'Daltfresh', '2023',24);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (25, 'Overhold', '2023',25);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (26, 'Kanlam', '2023',26);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (27, 'Greenlam', '2023',27);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (28, 'Latlux', '2023',28);
insert into Sach (id, tenSach, namXuatBan,idTacGia) values (29, 'Konklab', '2023',29);
categories